### ISSUE TITLE
General remark : open timing on the app far too short

### ISSUE THREAD

**Issue by Axel-2022** [Axel-2022/Finasset#2]
The time I write an issue and then Finasset is already gone : must go back to thinfinity and relaunch.

That is a problem for professional who do some other things and then will have to get back to our app.

Is it linked to Thinfinity ? Can it be "permanent" open ? (Or at least very longer).

**Comment by JohanDebeuckeleer** [comment]
= Thinfinity, not relevant at this moment
Please close issue
