### ISSUE TITLE
NEW F10 => Taal keuze moet ook in het Duits zijn (4 talen dus)

### ISSUE THREAD

**Issue by Axel-2022** [Axel-2022/Finasset#4]

**Comment by JohanDebeuckeleer** [comment]
[AfschrAppVertalingen.zip](https://github.com/Axel-2022/Finasset/files/10113853/AfschrAppVertalingen.zip)
In dit Excel bestand staan alle vertalingen voor Finasset
Hier kunnen nog extra kolommen worden toegevoegd om meer talen te ondersteunen.
Momenteel is dit voorzien op 2 talen, maar dat kunnen er meer worden.
Dit is nu enkel maar mogelijk omdat Belcofin en Accowin nog eeen andere methode van vertalen gebruiken. Daar moeten de bertalingen nu nog worden toegevoegd via Delphi. In Finasset moet de macro in het Excel bestand worden aangepast en uitgevoerd.
