### ISSUE TITLE
NEW F10 => email field

### ISSUE THREAD

**Issue by Axel-2022** [Axel-2022/Finasset#5]
There should be the possibility to enter more than one email (undefined with + button (add)). 

If there is/are function(s) associated with "main" email then possibility to select one email (like "preferred printer" if you have many printers => preferred email or main email)

**Comment by JohanDebeuckeleer** [comment]
In Belcofin kunnen we bij de aangevers meerdere mailadressen ingeven.
Daar is dat veld een TDBMemo met scrollbar  (in de database CLOB = memo)

In Finasset is dat een VARCHAR(255) = string  ==> beperkt in lengte

Meerdere mailadressen kunnen altijd worden ingegeven gescheiden met een comma-punt 
mail1@xx.x**;**mail2@yy.yy

**Comment by Axel-2022** [comment]
Ja ok maar... het is niet "handig" or "friendly" or "intuitive" => we must improve met "select" en "+" (toevogen) knopjes.

**Comment by Axel-2022** [comment]
> In Belcofin kunnen we bij de aangevers meerdere mailadressen ingeven. Daar is dat veld een TDBMemo met scrollbar (in de database CLOB = memo)
> 
> In Finasset is dat een VARCHAR(255) = string ==> beperkt in lengte
> 
> Meerdere mailadressen kunnen altijd worden ingegeven gescheiden met een comma-punt [mail1@xx.x](mailto:mail1@xx.x)**;**[mail2@yy.yy](mailto:mail2@yy.yy)

**Ja ok maar... het is niet "handig" or "friendly" or "intuitive" => we must improve met "select" en "+" (toevogen) knopjes.**
