### ISSUE TITLE
Upper bar : missing text

### ISSUE THREAD

**Issue by Axel-2022** [Axel-2022/Finasset#9]
In the main screen, missing texts on the menu

Dossiers (same in French) - Actieve boekjaar - Boekjaren - Alg. rek. - Invest. groep - Investeringen - Rapporten
Dossiers - Ex. actif - Exercices - Comptes gén. - Groupes d'invest. - Investissements - Rapports

De twee knopjes met taal (NL FR) -> graag één select knopje (niet beide talen altijd) => moet ook 4 talen zijn

**Comment by JohanDebeuckeleer** [comment]
4 talen?
Er zijn voor de officële documenten maar 2 talen.
We kunnen het programma in meerdere talen laten werken, maar dan moeten al die vertalingen er worden ingezet en moet de vertaalprocedure worden aangepast. Het kan natuurlijk, maar de officiële rapporten gaan we toch maar in 2 talen doen?

**Comment by Axel-2022** [comment]
Officiële rapporten moeten toch in het Duits bestaan ? En natuurlijk niet in het Engels maar in het Duits zeker. In het Engels is het meer voor gebruikers die buiten België werken.
